name: Cargo Check

on:
  push:
    paths-ignore:
       - '**.md'
    branches:
      - 'main'
  pull_request:
    paths-ignore:
       - '**.md'

jobs:
  cargo-check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test buildjet provider on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3

      - run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: ./
        with:
          workspaces: tests

      - run: |
          cargo check
          cargo test
          cargo build --release
        working-directory: tests
